### PR TITLE
2.1: cleanup: remove tools dir from PATH

### PR DESCRIPTION
**Pull request by tmds**
This is part of the dotnet scl enable script.

### CODE REVIEW

**Comment by tmds** [comment]
Thanks for reviewing @aslicerh .

CI is failing with `Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock`. Maybe Docker is dead on the CI server.

**Comment by aslicerh** [comment]
@tmds Yeah, I noticed that last week. The docker service is running, but the user that the bot runs as doesn't seem to have permission to talk with it now (for some reason). I added the user to the docker group last week, but it looks like I may need to get it to initiate a new session so that the group changes take effect.

**Comment by aslicerh** [comment]
[cibuild]

**Comment by tmds** [comment]
[cibuild]

test has timed out

**Pull request merged**
