### PR TITLE
Template to deploy dotnetcore 1.1 s2i

### PR DESCRIPTION
**Pull request by mglantz**
I've created a template to deploy dotnetcore 1.1 s2i apps. It includes asking for ASPNETCORE_URLS (required). Tested and works.

### CODE REVIEW

**Comment by jerboaa** [comment]
[skipci]

**Comment by jerboaa** [comment]
@mglantz Thanks for the contribution. I'm a bit unsure what problem this is trying to solve. For a couple of reasons:

1. There is already this "Try it" mechanism via the dotnet:1.1 imagestream, which seems to do the same thing. This is released.
2. There is this template for the to-be-released new sample app: https://github.com/redhat-developer/s2i-dotnetcore-ex/blob/dotnetcore-1.1/templates/aspnet-s2i-template.json Readme is here: https://github.com/redhat-developer/s2i-dotnetcore-ex/tree/dotnetcore-1.1

Are those not good enough? If so, why? Thanks!

**Comment by mglantz** [comment]
@jerboaa Hey, I did not see those. I'll try em out for size :-)

**Comment by jerboaa** [comment]
Closing for now. Please re-open if there is a use-case still not covered with the above.

**Pull request closed without merging**
