### PR TITLE
3.0 initial

### PR DESCRIPTION
**Pull request by tmds**
I've added a dev_30 branch which has a 3.0 folder, cp of 2.2.
This PR updates that folder for 3.0, and uses Microsoft 3.0 preview sdk for testing.

### CODE REVIEW

**Comment by tmds** [comment]
Tests passed on this PR using podman on Fedora 30 with centos images.

**Comment by omajid** [comment]
Looks good to me. Could you add the RHEL 8 stuff too? I think it only exists in 2.1 in this repo.

**Comment by tmds** [comment]
I've verified rhel7 and rhel8 images build and tests pass using `docker` and `s2i` on a rhel7 vm.

**Comment by azixaka** [comment]
Could you please tell when will this get merged into master? And when will the .net core 3.0 images become available in the RH Container Catalogue?

**Pull request merged**
