### PR TITLE
Add .NET Core 1.1 release

### PR DESCRIPTION
**Pull request by omajid**
This is based on a copy of 1.0, with 1.0 -> 1.1 changes from rh-dotnetcore11-docker applied

### CODE REVIEW

**Comment by jerboaa** [comment]
It builds fine, but the top-level README needs an update too, please.

**Comment by omajid** [comment]
@jerboaa, does the updated README look okay?

**Comment by jerboaa** [comment]
Looks good to me.

**Comment by jerboaa** [comment]
Thanks! Merged.

**Comment by jerboaa** [comment]
[skipci]

**Pull request merged**
