### PR TITLE
Add DOTNET_RESTORE_CONFIGFILE

### PR DESCRIPTION
**Pull request by tmds**
This envvar can be used to specify a NuGet.Config file to be used for restore operations.
It allows for more advanced use-cases than the existing DOTNET_RESTORE_SOURCES such as
specifying credentials, or providing the configuration via a file in the repository,
or a volume that is mounted in the container.

### CODE REVIEW

**Comment by omajid** [comment]
I always struggle with exposing things at the right granularity. So I am wondering: why do we choose not to expose something like `DOTNET_RESTORE_OPTIONS` directly?

I am wondering why it makes sense to try and make the build work if the file is missing. Shouldn't we error out loudly if a config file has been set but not found?

**Comment by tmds** [comment]
Good questions.

> I always struggle with exposing things at the right granularity. So I am wondering: why do we choose not to expose something like DOTNET_RESTORE_OPTIONS directly?

Open-ended options are problematic. We can't assume what the user has specified, so we can't make changes that we know to be non-breaking.

> I am wondering why it makes sense to try and make the build work if the file is missing. Shouldn't we error out loudly if a config file has been set but not found?

I implemented it like that because:
- the build is (very likely) going to fail at restore
- it enables to put a value in a common BuildConfig template that is a convention. That is, if the file is put at that location it will be used.

If you prefer to treat it as an error, I'm fine with dropping the convention feature.

**Comment by omajid** [comment]
Is there a general convention common in kubernetes/openshift for options with invalid values like this? What do other s2i builder images do? I would like to stick to the convention (if there's one). If not, I would lean towards error'ing out as early as possible; this leaves open the option of switching to a more lenient version later on.

**Comment by tmds** [comment]
`dotnet restore` picks up `NuGet.Config` without it having to be specified as a parameter and falls back if it isn't there.

I'll remove it. I don't expect we'll change it at a later point.

**Comment by tmds** [comment]
This is ok for CI.

@omajid @aslicerh can you approve the PR?

**Comment by tmds** [comment]
@aslicerh can you approve this one too?

**Comment by tmds** [comment]
Thanks for reviewing @aslicerh @omajid !

**Pull request merged**
