### PR TITLE
[README] Add a link to dotnet-example's sample usage.

### PR DESCRIPTION
**Pull request by jerboaa**
This depends on https://github.com/redhat-developer/s2i-dotnetcore-ex/pull/26

Rendered page here:
https://github.com/jerboaa/s2i-dotnetcore/tree/readme_reference_template_usage

[skipci]

### CODE REVIEW

**Comment by tmds** [comment]
I added general template usage instructions to the dotnet-pgsql-persistent PR. They cover both templates. If they are ok for you, we can close this PR without merging.

**Comment by jerboaa** [comment]
@tmds IMHO it would be good to have both. The template section of `s2i-dotnetcore-ex` talks in a bit more detail about how one would use the template to produce a 1.1 .NET Core build rather than 1.0 (the default). A crosslink does not hurt, does it?

**Comment by tmds** [comment]
I prefer to have the usage instructions in the same repo as the templates and would avoid having similar instructions in various repositories.

**Comment by jerboaa** [comment]
OK.

**Pull request closed without merging**
