### PR TITLE
DOTNET_STARTUP_PROJECT and DOTNET_TEST_PROJECTS can be csproj files

### PR DESCRIPTION
**Pull request by tmds**

### CODE REVIEW

**Comment by tmds** [comment]
[cibuild]

**Comment by tmds** [comment]
I don't get the Jenkins build log.
It's complaining about pushd, but that has been removed in the previous commit.

> E0503 07:56:50.585737 15347 util.go:91] /usr/libexec/s2i/assemble: line 63: pushd: test/test1/test1.csproj: Not a directory

**Comment by aslicerh** [comment]
This may be off, but is the assemble file at /usr/libexec/s2i/assemble the one from this branch or is it a pre-installed (or older) version?

**Comment by tmds** [comment]
[cibuild]

**Comment by tmds** [comment]
@aslicerh it should use the version that is on the branch. I just saw the jenkins config is responsible for deleting the images and added 20.

**Pull request merged**
