### PR TITLE
Use 'Invariant' culture

### PR DESCRIPTION
**Pull request by tmds**
.NET Core determines the culture based on the LANG environment variable.
By setting to 'C.UTF-8', we were using the 'en-US-POSIX' culture.
By not setting LANG, .NET uses the 'Invariant' culture.

- Not setting LANG is consistent with Microsoft .NET Core images.
- Performance for the Invariant culture is better than the 'en-US-POSIX' culture.

### CODE REVIEW

**Comment by tmds** [comment]
Technically this is a breaking change. Since the 'en-US-POSIX' culture is not common on workstation/images, in practice, this will be more a _not-breaking_ change. :smile:

**Comment by aslicerh** [comment]
Yeah, I was concerned about the possibility of this breaking a customer configuration at first, but that situation isn't likely. If they needed support for something other than english, they probably already set their LANG in their image. If they use english, most people will use the invariant default. Very few people probably go out of their way to use english unicode.

So yeah, this works for me.

**Comment by tmds** [comment]
Build failed with timeout:
```
++ '[' 7 -eq 7 -a 31 -le 30 ']'
++ '[' 7 -ne 0 ']'
++ error 'curl: (7) Failed connect to 172.17.0.2:8080; Connection refused'
++ echo -e '[ERROR] curl: (7) Failed connect to 172.17.0.2:8080; Connection refused'
[ERROR] curl: (7) Failed connect to 172.17.0.2:8080; Connection refused
```

**Comment by tmds** [comment]
[cibuild]

**Comment by tmds** [comment]
Thanks for reviewing @omajid @aslicerh

**Pull request merged**
