### PR TITLE
s2i/bin/run: remove support for arguments.txt

### PR DESCRIPTION
**Pull request by tmds**
.NET has support for reading configuration in 'Microsoft.Extensions.Configuration'.
There are providers that read Xml, Ini and Json configuration files.

Remove dotnetbot test which was testing arguments.txt.
Convert qotd test to use 'Microsoft.Extensions.Configuration.Json' instead of
arguments.txt

### CODE REVIEW

**Comment by jerboaa** [comment]
How do we support dotnet apps which actually use the `args[]` array in `Main`? This change seems to suggest that we'd be requiring apps to do some porting work to use `Microsoft.Extenstions.Configuration` instead. The idea of the image is to support as many apps out there as possible without requiring changes to the apps code itself. This isn't a drop-in replacement for `arguments.txt` as far as I'm aware.

Thoughts?

**Comment by tmds** [comment]
> How do we support dotnet apps which actually use the args[] array in Main? This change seems to suggest that we'd be requiring apps to do some porting work to use Microsoft.Extenstions.Configuration instead. The idea of the image is to support as many apps out there as possible without requiring changes to the apps code itself. This isn't a drop-in replacement for arguments.txt as far as I'm aware.
> 
> Thoughts?

Most applications will be configurable by environment variables or files, so those won't have a problem.
The very few applications that are only configurable by the command line can be changed easily. I recommend using `Microsoft.Extenstions.Configuration` since it is standardized and powerful. Something like this will do the job too:

```
if (File.Exists("arguments.txt"))
{
    args = args.Concat(File.ReadAllText("arguments.txt").Trim().Split()).ToArray();
}
```

**Comment by jerboaa** [comment]
@omajid What are your thoughts about this? I am personally OK with this. It would be good to have some documentation for arguments handling. Including our recommendations.

**Comment by omajid** [comment]
@jerboaa I looked around and I don't see any other s2i images that use arguments.txt. If arguments.txt is a common pattern, we should keep it.

Various sources on modern microservices suggest keeping entire configuration in environment variables; so not supporting arguments.txt seems fine too.

**Comment by jerboaa** [comment]
@omajid OK, thanks.

@tmds Can I ask for some documentation, pretty please? I'm fine with a separate patch :)

**Comment by tmds** [comment]
> @tmds Can I ask for some documentation, pretty please? I'm fine with a separate patch :)

This is covered in the ASP.NET Core Fundamentals:

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration

**Comment by jerboaa** [comment]
> This is covered in the ASP.NET Core Fundamentals:

I don't agree. While this covers how to handle config in your app, it does not explain how a user is supposed to pass arguments to a .NET Core app in the s2i environment. Provided that app does something with the args array in Main() only. Anyway, something to hash out in a separate PR.

**Comment by jerboaa** [comment]
I'm going to merge this. We'll figure out the documentation issue in a separate PR.

**Pull request merged**
