### PR TITLE
Add tests for CLI apps and top-level build.sh

### PR DESCRIPTION
**Pull request by jerboaa**
Also add top-level build.sh so as to be able to drive
building/testing of all versions.

Example building all images, running tests on them:

  $ sudo ./build.sh

Example building 1.0 image and running tests on it:

  $ sudo VERSIONS=1.0 ./build.sh

### CODE REVIEW

**Comment by jerboaa** [comment]
@omajid @tmds @gpiercey Please take a look.

**Comment by tmds** [comment]
:+1: works fine except for the dotnetbot which is failing on my machine:
```
[INFO] Test CLI app: dotnetbot FAILED.

expected:

-------->8
foobarbaz
8<--------

but got:

-------->8
ERROR: ld.so: object 'libnss_wrapper.so' from LD_PRELOAD cannot be preloaded: ignored.
ERROR: ld.so: object 'libnss_wrapper.so' from LD_PRELOAD cannot be preloaded: ignored.
---> Running application with arguments from file 'arguments.txt' ...
8<--------
```

**Comment by jerboaa** [comment]
`ERROR: ld.so: object 'libnss_wrapper.so' from LD_PRELOAD cannot be preloaded: ignored.` Seems like something unrelated. Can this be reproduced with running the built s2i image on dotnetbot too?

**Comment by jerboaa** [comment]
For the record, Toms failure was caused by a broken image build. His image didn't have nss_wrapper installed. Somebody, please merge! :)

**Comment by tmds** [comment]
> For the record, Tom's failure was caused by a broken image build. His image didn't have nss_wrapper installed. Somebody, please merge! :)

The yum install nss_wrapper gives this output: "No package nss_wrapper available.". How can I resolve this?

Also I can't build unless I `setenforce 0`.

**Comment by jerboaa** [comment]
> The yum install nss_wrapper gives this output: "No package nss_wrapper available.". How can I resolve this?

Enable the relevant OSE repository with nss_wrapper in it.

**Comment by jerboaa** [comment]
@tmds OK to merge? We should address the SELinux issue separately.

**Comment by tmds** [comment]
> Enable the relevant OSE repository with nss_wrapper in it.

This needs to be done on the machine where build.sh is invoked? Why doesn't the Dockerfile include these repositories? Can you document the dependencies?

> @tmds OK to merge? We should address the SELinux issue separately.

For me it's ok to address the SELinux issue separately. Once I get it working on my machine (nss_wrapper) we are ok to merge.

**Comment by jerboaa** [comment]
> This needs to be done on the machine where build.sh is invoked? Why doesn't the Dockerfile include these repositories? Can you document the dependencies?

First question: yes. Second question: https://github.com/redhat-developer/s2i-dotnetcore/blob/master/1.0/Dockerfile.rhel7#L41 enables the repository in question.

Third question: From the installation section of our main README[1]:

"To build a RHEL 7 based .NET Core image, you need to run the build on a properly subscribed RHEL machine."

Feel free to add a section with the commands to subscribe to the relevant RHEL channels.

**Comment by tmds** [comment]
> Third question: From the installation section of our main README[1]:
> 
> "To build a RHEL 7 based .NET Core image, you need to run the build on a properly subscribed RHEL machine."
> 
> Feel free to add a section with the commands to subscribe to the relevant RHEL channels.

@jerboaa how can I figure out these commands?

**Comment by jerboaa** [comment]
@tmds https://access.redhat.com/documentation/en/net-core/1.1/single/getting-started-guide/#gs_install_dotnet has some info about how to subscribe to channels and register the machine.

**Comment by tmds** [comment]
> @tmds https://access.redhat.com/documentation/en/net-core/1.1/single/getting-started-guide/#gs_install_dotnet has some info about how to subscribe to channels and register the machine.

Went through those steps when I installed dotnet. I am looking for the steps to install libnss_wrapper. Where can I find those?

**Comment by jerboaa** [comment]
[skipci]

**Pull request closed without merging**
