### PR TITLE
Switch to new sample app in imagestreams.

### PR DESCRIPTION
**Pull request by jerboaa**
Use s2i-dotnetcore-ex rather than in-tree <version>/test/asp-net-hello-world.

### CODE REVIEW

**Comment by jerboaa** [comment]
@omajid @tmds OK to merge? FWIW, OpenShift QA has OK'ed it. I'd like to hand this off to OpenShift people to incorporate into a release. Thanks!

**Comment by jerboaa** [comment]
[skipci]

**Comment by tmds** [comment]
:+1: :shipit:

**Comment by jerboaa** [comment]
Thanks!

**Pull request merged**
