### PR TITLE
Add support for running test project in assemble via DOTNET_TEST_PROJECTS

### PR DESCRIPTION
**Pull request by tmds**

### CODE REVIEW

**Comment by tmds** [comment]
@jerboaa ptal

**Comment by jerboaa** [comment]
I'm going to look at it today.

**Comment by jerboaa** [comment]
When I run tests on this I'm getting:
```
---> Running test project: test/test1...
E1219 08:53:24.985867 15191 util.go:91] Project test1 does not have a lock file. Please run "dotnet restore" to generate a new lock file.
E1219 08:53:24.986895 15191 util.go:91] Project test1 does not have a lock file. Please run "dotnet restore" to generate a new lock file.
E1219 08:53:26.541176 15191 main.go:352] An error occurred: non-zero (13) exit code from dotnet/dotnetcore-10-rhel7

[INFO] TEST FAILED (1)
```

Looks like a `dotnet restore` is missing somewhere.

**Comment by tmds** [comment]
@jerboaa did it work on 1.1?

**Comment by tmds** [comment]
Looks like it works well outside the s2i container:
```
[tmds@rexhl asp-net-hello-world-envvar]$ dotnet restore
log  : Restoring packages for /home/tmds/repos/s2i-dotnetcore/1.0/test/asp-net-hello-world-envvar/test/test1/project.json...
log  : Restoring packages for /home/tmds/repos/s2i-dotnetcore/1.0/test/asp-net-hello-world-envvar/test/test2/project.json...
log  : Restoring packages for /home/tmds/repos/s2i-dotnetcore/1.0/test/asp-net-hello-world-envvar/src/lib/project.json...
log  : Restoring packages for /home/tmds/repos/s2i-dotnetcore/1.0/test/asp-net-hello-world-envvar/src/app/project.json...
warn : Dependency specified was dotnet-test-xunit (>= 1.0.0-rc2-192208-24) but ended up with dotnet-test-xunit 1.0.0-rc2-build10015.
warn : Dependency specified was dotnet-test-xunit (>= 1.0.0-rc2-192208-24) but ended up with dotnet-test-xunit 1.0.0-rc2-build10015.
log  : Writing lock file to disk. Path: /home/tmds/repos/s2i-dotnetcore/1.0/test/asp-net-hello-world-envvar/src/lib/project.lock.json
log  : /home/tmds/repos/s2i-dotnetcore/1.0/test/asp-net-hello-world-envvar/src/lib/project.json
log  : Restore completed in 4375ms.
log  : Writing lock file to disk. Path: /home/tmds/repos/s2i-dotnetcore/1.0/test/asp-net-hello-world-envvar/src/app/project.lock.json
log  : /home/tmds/repos/s2i-dotnetcore/1.0/test/asp-net-hello-world-envvar/src/app/project.json
log  : Restore completed in 9692ms.
log  : Writing lock file to disk. Path: /home/tmds/repos/s2i-dotnetcore/1.0/test/asp-net-hello-world-envvar/test/test2/project.lock.json
log  : /home/tmds/repos/s2i-dotnetcore/1.0/test/asp-net-hello-world-envvar/test/test2/project.json
log  : Restore completed in 9827ms.
log  : Writing lock file to disk. Path: /home/tmds/repos/s2i-dotnetcore/1.0/test/asp-net-hello-world-envvar/test/test1/project.lock.json
log  : /home/tmds/repos/s2i-dotnetcore/1.0/test/asp-net-hello-world-envvar/test/test1/project.json
log  : Restore completed in 9892ms.
[tmds@rexhl asp-net-hello-world-envvar]$ cd test/test1
[tmds@rexhl test1]$ dotnet test
Project test1 (.NETCoreApp,Version=v1.0) will be compiled because expected outputs are missing
Compiling test1 for .NETCoreApp,Version=v1.0
/home/tmds/repos/s2i-dotnetcore/1.0/test/asp-net-hello-world-envvar/test/test1/project.json(9,46): warning NU1007: Dependency specified was dotnet-test-xunit >= 1.0.0-rc2-192208-24 but ended up with dotnet-test-xunit 1.0.0-rc2-build10015.

Compilation succeeded.
    1 Warning(s)
    0 Error(s)

Time elapsed 00:00:02.6304217
 

xUnit.net .NET CLI test runner (64-bit rhel.7.3-x64)
  Discovering: test1
  Discovered:  test1
  Starting:    test1
  Finished:    test1
=== TEST EXECUTION SUMMARY ===
   test1  Total: 1, Errors: 0, Failed: 0, Skipped: 0, Time: 0.486s
SUMMARY: Total: 1 targets, Passed: 1, Failed: 0.
```

**Comment by jerboaa** [comment]
Could you please rebase this onto latest master? Or at least resolve conflicts?

**Comment by jerboaa** [comment]
> @jerboaa did it work on 1.1?
I didn't try.

**Comment by jerboaa** [comment]
Tests pass. LGTM.

**Comment by jerboaa** [comment]
[skipci]

**Pull request merged**
