### PR TITLE
Add note about waiting on upstream packages for Centos and .NET 5.0

### PR DESCRIPTION
**Pull request by aslicerh**

### CODE REVIEW

**Review by omajid — APPROVED** [review]
Thanks, this should make things better for our users.

What do you think about leaving "CentOS 7" out entirely until we know it's working?

**Comment by aslicerh** [comment]
@omajid My only issue with that is that it might be confusing to not mention it, but then have the Dockerfile for it anyway, and to have that documented in the version READMEs. And I'm not sure we want to remove all the centos related stuff for 5.0 just because there aren't upstream packages yet, though I guess we could.

**Comment by omajid** [comment]
Fair enough.

**Comment by tmds** [comment]
> And I'm not sure we want to remove all the centos related stuff for 5.0

I don't think anyone would benefit from this.

Proposed changes look good to me.

**Review by tmds — APPROVED** [review]

**Pull request merged**
