### PR TITLE
Mark latest imagestreams as hidden

### PR DESCRIPTION
**Pull request by yselkowitz**
.NET application source code includes a hardcoded version in
TargetFramework, so unlike other SCLs, using a floating tag
won't consistently work.

Closes: https://github.com/redhat-developer/s2i-dotnetcore/issues/336

### CODE REVIEW

**Review by tmds — APPROVED** [review]

**Comment by tmds** [comment]
@aslicerh @omajid can you confirm you're ok with hiding `latest` based on the discussion in https://github.com/redhat-developer/s2i-dotnetcore/issues/336?

**Comment by tmds** [comment]
ping @omajid @aslicerh

**Comment by omajid** [comment]
What is the user experience change on OpenShift? Is it just that "Latest" is no longer offered as an option?

**Comment by yselkowitz** [comment]
`latest` won't show in the console UI, but will still be available to templates and from the command line with `oc`.

**Pull request merged**
