### PR TITLE
DEV_MODE improvements

### PR DESCRIPTION
**Pull request by tmds**
Adding some debug statements to figure out why CI is failing on https://github.com/redhat-developer/s2i-dotnetcore/pull/126

### CODE REVIEW

**Comment by tmds** [comment]
CI was successful, it seems the timeout we have for the change test is on the edge:
```
++ '[' 7 -eq 7 ']'
++ sleep 1
++ attempt=29
++ '[' 7 -eq 7 -a 29 -le 30 ']'
+++ curl -sS http://172.17.0.2:8080/
++ output='Hello World!'
++ rv=0
++ '[' 0 -eq 7 ']'
++ attempt=30
++ '[' 0 -eq 7 -a 30 -le 30 ']'
++ '[' 0 -ne 0 ']'
++ echo 'Hello World!'
+ local 'response=Hello World!'
```

**Comment by aslicerh** [comment]
Do you want to turn this into a PR increasing the retry attempts? Or do you want me adding that to the #126?

**Comment by tmds** [comment]
> Do you want to turn this into a PR increasing the retry attempts? Or do you want me adding that to the #126?

The first. Going to remove the `-R` flag in next commit.

**Comment by tmds** [comment]
[cibuild]

**Comment by tmds** [comment]
[cibuild]

**Comment by tmds** [comment]
[cibuild]

**Comment by tmds** [comment]
[cibuild]

**Pull request merged**
