### PR TITLE
Update dotnet-example template for 2.0

### PR DESCRIPTION
**Pull request by jerboaa**
We are going to merge this once 2.0 images will be available.

### CODE REVIEW

**Comment by tmds** [comment]
Can you remove setting `DOTNET_PUBLISH` from the template?

**Comment by tmds** [comment]
Include dotnet-pgsql-persistent.json in this PR too?

**Comment by jerboaa** [comment]
> Include dotnet-pgsql-persistent.json in this PR too?

I'm not there, yet so will be a separate PR, since I've not tested it yet.

**Comment by jerboaa** [comment]
> Can you remove setting DOTNET_PUBLISH from the template?

Do you mean removing this [environment variable](https://github.com/redhat-developer/s2i-dotnetcore/blob/master/templates/dotnet-example.json#L111)? Wouldn't this *not* publish if used like so:

    $ oc new-app --template=dotnet-example --param=DOTNET_IMAGE_STREAM_TAG=dotnet:1.1 --param=SOURCE_REPOSITORY_REF=dotnetcore-1.1

**Comment by tmds** [comment]
I see, yes, when using the template to instantiate a 1.x project it would require the variable still.

**Comment by jerboaa** [comment]
Once there are no active 1.x images any more we can remove it.

**Pull request merged**
