### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by ibecky**
fix dockerfile for centos7

### CODE REVIEW

**Comment by jerboaa** [comment]
@ibecky What's broken with the current CentOS 7 dockerfile? This is being built via the CentOS pipelines and last successful automated build was on July 16 (yesterday):
https://registry.centos.org/pipeline-logs/Y2U3Y2NhZjJhNT/

That image can get retrieved from the CentOS registry:
https://registry.centos.org/dotnet/dotnet-20-runtime-centos7

**Comment by jerboaa** [comment]
Sorry, wrong links:
build logs: https://registry.centos.org/pipeline-logs/NWNjYWMwNzhkZj
registry url: https://registry.centos.org/dotnet/dotnet-20-centos7

**Comment by ibecky** [comment]
@jerboaa wrong FROM image, 'dotnet/dotnet-20-runtime-centos7' is maybe private image for redhat registry. FROM image will be FROM centos:7 or FROM centos/s2i-core-centos7:latest.

**Comment by jerboaa** [comment]
@ibecky The build setup in the centos pipeline does not allow for hard-coded registry values in FROM IIRC. Hence no full registry URL in the Dockerfile. @aslicerh is right on that regard. You need the centos registry in your config. Try this, which worked for me on F28:

    $ cat /etc/containers/registries.conf | grep centos -C2
    registries:
      - registry.fedoraproject.org
      - registry.centos.org
      - registry.access.redhat.com
    $ sudo systemctl restart docker
    $ git clone git://github.com/redhat-developer/s2i-dotnetcore.git
    $ cd s2i-dotnetcore/2.0/runtime
    $ sudo docker build -t dotnet/dotnet-20-runtime-centos7 .
    $ cd ../build
    $ sudo docker build -t dotnet/dotnet-20-centos7 .

**Comment by jerboaa** [comment]
Closing this PR as I don't think it's an actual issue. Feel free to reopen if you feel otherwise.

**Pull request closed without merging**
