### PR TITLE
Dockerfile for dotnet 1.0 on Centos 7

### PR DESCRIPTION
**Pull request by yudhiwidyatama**
With this we could run dotnet 1.0 on centos 7 OS, useful when RHEL subscription aren't easily available.

### CODE REVIEW

**Comment by tmds** [comment]
I'm curious. Have you considered migrating to 2.0? There is already a centos image, and it moves you away from the deprecated project.json format?

**Comment by yudhiwidyatama** [comment]
Currently we contracted an external team to create an application, which unfortunately using dotnet 1.0, and nearing the end period of the contract. The Team lead stated that due to resource constraints and volume of changes needed they were unable to port it during this contract term.

**Comment by jerboaa** [comment]
Could you please update the tests to be able to run with the resulting image please?

https://github.com/redhat-developer/s2i-dotnetcore/blob/master/1.0/test/run#L17
and
https://github.com/redhat-developer/s2i-dotnetcore/blob/master/build.sh#L83

**Comment by yudhiwidyatama** [comment]
ok, I updated the 1.0/test/run and build.sh in revision 1a3b7e3

**Comment by jerboaa** [comment]
[cibuild]

**Comment by aslicerh** [comment]
This looks good to me as well, so I'm going to go ahead and merge it in.

**Comment by jerboaa** [comment]
@yudhiwidyatama Thanks for the contribution!

If you'd like the image to be auto-built in the centos registry, here would be the steps in order to get this done:

1. Add a `cccp.yml` file similar to [this](https://github.com/redhat-developer/s2i-dotnetcore/blob/master/2.0/build/cccp.yml) for `1.0` folder. Suggested job id `dotnetcore-10-centos7`
2. Add an entry to the centos container catalog, file [dotnet.yml](https://github.com/CentOS/container-index/blob/master/index.d/dotnet.yml) for the `dotnet/dotnetcore-10-centos7` image.

After that's in, it should get built and pushed to the centos registry automatically.

**Pull request merged**
