### PR TITLE
Cleanup NuGet development artifacts

### PR DESCRIPTION
**Pull request by tmds**
For a standard ASP.NET Core webapp we are pushing almost 500MB of downloaded artifacts into the deployment image.

```
$ du -hs .local .nuget                                                                                                                                                                                                       
133M    .local                                                                                                                                                                                                                     
349M    .nuget
```

### CODE REVIEW

**Comment by jerboaa** [comment]
[cibuild]

**Comment by jerboaa** [comment]
CI failed with:

    E0921 09:43:44.318960 07477 main.go:342] An error occurred: building registry.access.redhat.com/dotnet/dotnet-20-rhel7:latest-sample failed when committing the image due to error: API error (500): {"message":"ApplyLayer exit status 1 stdout:  stderr: write /opt/app-root/.nuget/packages/microsoft.aspnetcore.mvc.core/2.0.0/microsoft.aspnetcore.mvc.core.2.0.0.nupkg.sha512: read-only file system"}

Do we need empty `~/.nuget ~/.local` directories with permissions fixed?

**Comment by tmds** [comment]
[cibuild]

**Comment by tmds** [comment]
[cibuild]

**Comment by aslicerh** [comment]
[cibuild]

**Comment by tmds** [comment]
@aslicerh fyi, I've updated the ci config to rm all containers and images, to see if the error persists even then

**Comment by aslicerh** [comment]
@tmds Yeah, but that change was causing a failure also. I updated it so it wouldn't fail (and kicked off another build).

**Comment by tmds** [comment]
Glad that got rid of the error

**Pull request merged**
