### PR TITLE
Properly run assembly as PID 1.

### LINKED ISSUE #21: dotnet process not PID 1 when run
When I run an s2i built image in Docker `dotnet` is not the process with PID 1. I'm seeing:
```
$ ps ax                                    
  PID TTY      STAT   TIME COMMAND                                     
    1 ?        SLsl   0:55 dotnet run                   
   78 ?        SLl    0:09 /opt/rh/rh-dotnetcore10/root/usr/lib64/dotnetcore/dotnet exec --additionalprobingpath /opt/app-root/src/.nuget/packages /opt/app-root/src/bin/Debug/netcoreapp1.0/src.dll
```

or
```
$ ps ax                                             
  PID TTY      STAT   TIME COMMAND    
    1 ?        Ss     0:00 /bin/bash /usr/libexec/s2i/run         
   18 ?        SLl    0:02 dotnet ./bin/Release/netcoreapp1.0/src.dll
```

See https://github.com/openshift-s2i/s2i-aspnet-example/commit/9bf016b826711e79248704c783f574768cbc7f49. We should use `exec`.

### PR DESCRIPTION
**Pull request by jerboaa**
Closes #21.

### CODE REVIEW

**Comment by jerboaa** [comment]
@tmds @omajid Could you have a look please?

**Comment by tmds** [comment]
:shipit:

**Comment by jerboaa** [comment]
Thanks!

**Comment by jerboaa** [comment]
skipci

**Pull request merged**
