### PR TITLE
Add .NET Core 3.1 imagestream for CentOS 7

### PR DESCRIPTION
**Pull request by omajid**

### CODE REVIEW

**Comment by aslicerh** [comment]
2.2 went EOL. Do we also want to go ahead and remove those entries?

**Comment by omajid** [comment]
Yes. I want to do that as a separate patch since it involved other distributions too. Are you okay with that?

**Comment by aslicerh** [comment]
Absolutely. Just thought I'd ask for this while it was being changed, but I am very ok with having one patch for all of 2.2 obsoletion.

**Comment by aslicerh** [comment]
In fact, are you working on that already? Because if not I can get on that myself.

**Comment by omajid** [comment]
> In fact, are you working on that already? Because if not I can get on that myself.

I haven't started on it; I wanted to finish testing this first. But I would be more than happy if you can take care of removing the EOL versions.

**Comment by aslicerh** [comment]
> I would be more than happy if you can take care of removing the EOL versions.

Consider it mine then. PR incoming.

**Comment by aslicerh** [comment]
I verified this on my own CRC instance. Looks good to me.

**Comment by omajid** [comment]
Thanks!

**Pull request merged**
