### PR TITLE
Remove .NET 5 imagestreams

### PR DESCRIPTION
**Pull request by yselkowitz**
.NET 5 just went out of support.

https://access.redhat.com/support/policy/updates/net-core

### CODE REVIEW

**Comment by omajid** [comment]
FWIW, upstream released an update for .NET 5 just a day after .NET 5 went EOL :shrug: 

We are going to try and ship that update out before we look at marking .NET 5 as EOL.

**Comment by yselkowitz** [comment]
We are currently working on curating imagestream updates for OpenShift 4.11.  Even if you do release one last update for existing users (which won't be affected by this), certainly we don't want to continue making this available in OpenShift for another 18 months (after 4.11 GA).  Generally, we remove unsupported imagestream versions as they go out of support.  However, if you really think it's too early, then we should at least tag it as `hidden` so that it's not displayed in the web console for creating new builds, and remove it for 4.12.  Which do you prefer?

**Comment by aslicerh** [comment]
I think this is fine. It won't affect existing users, only new ones. And even if someone did come in and want to use 5.0 images, they wouldn't need a proper imagestream because the `latest` is never going to change.

**Review by aslicerh — APPROVED** [review]

**Comment by aslicerh** [comment]
I haven't heard any other commentary about this, and 5.0 is EOL and the final container has been released. I'm going to go ahead and merge this.

**Pull request merged**
