### PR TITLE
DOTNET_FRAMEWORK should not be configurable by users.

### LINKED ISSUE #15: DOTNET_FRAMEWORK should not be configurable by users.
While we should pass the explicit framework to build the app for, we shouldn't allow for users to configure it themselves. It doesn't make sense in the s2i context. Take for example the MusicStore app. It targets `net451` and `netcoreapp1.1`[1]. It will only build successfully, with the .NET Core 1.1 image, when netcoreapp1.1 is explicitly passed to the `dotnet build` command.

For the 1.0 .NET Core builder image it should build for, well, .NET Core 1.0 and similarly, for the 1.1 .NET Core builder image it should be using .NET Core 1.1.

[1] https://github.com/aspnet/MusicStore/blob/dev/samples/MusicStore/project.json#L57

### PR DESCRIPTION
**Pull request by jerboaa**
Closes #15. Depends on #16 and #17.

### CODE REVIEW

**Comment by tmds** [comment]
LGTM

**Comment by omajid** [comment]
Could you please also update the `README.md` files to remove the references to `DOTNET_FRAMEWORK`?

**Comment by jerboaa** [comment]
> Could you please also update the README.md files to remove the references to DOTNET_FRAMEWORK?

Of course!

**Comment by jerboaa** [comment]
@omajid done now. How does it look?

**Comment by jerboaa** [comment]
skipci

**Pull request merged**
