### PR TITLE
Added rsync to the 2.0 runtime image

### PR DESCRIPTION
**Pull request by aslicerh**
I'm adding this in response to Issue #118.

In that issue there was a question of how much faster rsync was and how much it would increase the size of the image.

I can't speak to the speed increase, but the size increase is .5 MB to the image.

In my opinion, if adding this would make using the images more convenient to users, that is an insignificant trade-off in return.

### CODE REVIEW

**Comment by omajid** [comment]
What does that 0.5 MB mean in terms of percentage? Is it less than 1%? Sounds like a sensible compromise to me.

**Comment by aslicerh** [comment]
@omajid On my system it went from 372 MB to 372.5 MB.

So , what, about .134%?

**Comment by tmds** [comment]
> I'm adding this in response to Issue #118.

@aslicerh The request is to add this to the **build** image to be able to upload source code and compile it.

**Comment by aslicerh** [comment]
@tmds Yes, but in theory you could do something similar by building on a local system and pushing it to a runtime image.

Either way rsync ends up in build image.

**Comment by tmds** [comment]
In theory :stuck_out_tongue: if we put *everything* in the runtime image, it ends up in the build image too.

**Comment by aslicerh** [comment]
@tmds but then we have to build an 'atmoic-runtime-image'. :)

Anyway, I'm going ahead and merging this. If someone cares enough to make a case to move it to build alone, then feel free.

**Comment by tmds** [comment]
> Anyway, I'm going ahead and merging this. If someone cares enough to make a case to move it to build alone, then feel free.

:confused: case:

>@aslicerh The request is to add this to the build image to be able to upload source code and compile it.

**Comment by aslicerh** [comment]
@tmds Yes, that is true. But if we're going to bother having rsync in one of the images I don't see why we wouldn't have it in both. There are valid use cases to use oc rsync in the runtime image, such as database backups and restores, pulling logs for monitoring scripts, etc.

That database example is even used in the dev docs for oc rsync:
https://docs.openshift.org/latest/dev_guide/copy_files_to_container.html

**Comment by tmds** [comment]
> There are valid use cases to use oc rsync in the runtime image, such as database backups and restores, pulling logs for monitoring scripts, etc.

- most users will be using the build image
- `oc rsync` works without `rsync`
- we made the runtime image to have a small image

It's not adding a lot... but I don't see a reason for it to be there.

**Comment by aslicerh** [comment]
@tmds Couldn't the same arguments apply to PR #120?

**Comment by tmds** [comment]
> @tmds Couldn't the same arguments apply to PR #120?

When you're using the runtime image for size reasons (that is the reason you are using it for), it's a high cost of having to switch to the build image to be able to debug, and only a low cost if we put it in the image.

**Pull request merged**
