### PR TITLE
update imagestreams to registry.redhat.io

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@tmds these changes are needed to switch to the new redhat registry, please let me know if you have any questions.

**Comment by omajid** [comment]
[cibuild]

**Comment by aslicerh** [comment]
@bparees In general, things look fine, but I have a couple of questions.

1) Why change the reference policy to local?
2) Is this new registry actually a different registry, or just a new front for the same registry?

**Comment by bparees** [comment]
@aslicerh 

1) it allows the images to be pulled by the internal openshift registry on your behalf, which simplifies credential management for users.

2) new front(with auth).  content is the same.

**Comment by bparees** [comment]
> Will that stop working?

well the imagestream will get created, but it won't import successfully unless you've got an appropriate secret in the namespace you created the imagestream in.  See:
https://docs.okd.io/latest/dev_guide/managing_images.html#private-registries

(because basically you can consider registry.redhat.io to be a private registry now)

**Comment by bparees** [comment]
(we automatically setup the secret in the `openshift` namespace, so imports will work there)

**Comment by tmds** [comment]
> (we automatically setup the secret in the openshift namespace, so imports will work there)

Does that require a minimum version of OpenShift?
What happens for other namespaces (not `openshift`)? Like when trying to add the latest version to an OpenShift Origin project as a user.

**Comment by bparees** [comment]
> Does that require a minimum version of OpenShift?

3.11 will create the secret.  For now, 3.10 and below will not (but the imagestreams they ship will keep pointing to the old registry), but we'll do an errata at some point to update them to the new imagestreams and add logic to create the secret.

> What happens for other namespaces (not openshift)? Like when trying to add the latest version to an OpenShift Origin project as a user.

they'll have to follow the doc i linked to create an appropriate secret or the import will fail.

**Comment by tmds** [comment]
We should update our docs with some steps on how to create the secret before merging this.

@bparees could we limit the change to the 2.1 version? (2.0 is EOL in October, 1.x is not used much and EOL next year)

**Comment by bparees** [comment]
> @bparees could we limit the change to the 2.1 version? (2.0 is EOL in October, 1.x is not used much and EOL next year)

i'd rather not, even though your image may go EOL, people can still have resources referencing the imagestream and when the old registry goes away, those references will break.  What is your motivation for not changing those?

**Comment by tmds** [comment]
I didn't expect the old url to stop working at some point. Is this something that will happen soon?

My question was to avoid having to update the docs for those older versions. We can update those docs too.

**Comment by bparees** [comment]
> I didn't expect the old url to stop working at some point. Is this something that will happen soon?

not "soon" per se, but soon enough that we'll all still be around when it happens :)

**Comment by bparees** [comment]
@tmds any other questions you need answered before merging this?

**Comment by tmds** [comment]
Our changes to the docs are live. This is good to merge. Thanks @bparees !

**Pull request merged**
